variables:
  TF_DIR: "GitLab/devops_first"

stages:
  - init
  - plan
  - apply

init:
  stage: init
  image:
    name: hashicorp/terraform:1.6.6
    entrypoint: ["/bin/sh", "-c"]
  script:
    - cd $TF_DIR
    - terraform init

plan:
  stage: plan
  image: hashicorp/terraform:1.6.6
  script:
    - cd $TF_DIR
    - ls -la
    - terraform plan -out=tfplan

apply:
  stage: apply
  image: hashicorp/terraform:1.6.6
  when: manual
  script:
    - cd $TF_DIR
    - terraform apply -auto-approve tfplan
