image: hashicorp/terraform:1.5.7

stages:
  - validate
  - plan
  - apply
  - destroy

default:
  before_script:
    - cd GitLab/devops_first

terraform_validate:
  stage: validate
  script:
    - terraform validate
  only:
    - main

terraform_plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - GitLab/devops_first/tfplan
  only:
    - main

terraform_apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - terraform_plan
  only:
    - main
  when: manual

terraform_destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  only:
    - main
  when: manual
