stages:
  - init
  - validate
  - plan
  - apply

variables:
  TF_DIR: "devops_first"

terraform_init:
  stage: init
  image:
    name: hashicorp/terraform:1.6.6
    entrypoint: [""]
  script:
    - cd $TF_DIR
    - terraform init -upgrade

terraform_validate:
  stage: validate
  image:
    name: hashicorp/terraform:1.6.6
    entrypoint: [""]
  script:
    - cd $TF_DIR
    - terraform validate

terraform_plan:
  stage: plan
  image:
    name: hashicorp/terraform:1.6.6
    entrypoint: [""]
  script:
    - cd $TF_DIR
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - $TF_DIR/tfplan

terraform_apply:
  stage: apply
  image:
    name: hashicorp/terraform:1.6.6
    entrypoint: [""]
  script:
    - cd $TF_DIR
    - terraform apply -auto-approve tfplan
  when: manual   # so it won’t run automatically, you must trigger it
