image: hashicorp/terraform:1.5.7

stages:
  - init
  - validate

terraform_init:
  stage: init
  script:
    - terraform --version
    - terraform init
  only:
    - main

terraform_validate:
  stage: validate
  script:
    - terraform validate
  only:
    - main
