stages:
  - init
  - validate
  - plan
  - apply

variables:
  TF_DIR: "GitLab/devops_first"

before_script:
  - echo "=== Current working directory ==="
  - pwd
  - echo "=== Repository tree ==="
  - ls -R

init:
  stage: init
  image: hashicorp/terraform:1.6.6
  script:
    - cd $TF_DIR
    - echo "=== Inside TF_DIR ==="
    - pwd
    - ls -la
    - terraform init -backend=false

validate:
  stage: validate
  image: hashicorp/terraform:1.6.6
  script:
    - cd $TF_DIR
    - ls -la
    - terraform validate

plan:
  stage: plan
  image: hashicorp/terraform:1.6.6
  script:
    - cd $TF_DIR
    - ls -la
    - terraform plan -out=tfplan

apply:
  stage: apply
  image: hashicorp/terraform:1.6.6
  when: manual
  script:
    - cd $TF_DIR
    - ls -la
    - terraform apply -auto-approve tfplan
