image:
  name: hashicorp/terraform:1.6.6
  entrypoint: [""]

variables:
  TF_DIR: "devops_first"

stages:
  - init
  - validate
  - plan
  - apply

# Stage 1: terraform init
terraform_init:
  stage: init
  script:
    - cd $TF_DIR
    - terraform init -upgrade
  only:
    - main

# Stage 2: terraform validate
terraform_validate:
  stage: validate
  script:
    - cd $TF_DIR
    - terraform validate
  only:
    - main

# Stage 3: terraform plan
terraform_plan:
  stage: plan
  script:
    - cd $TF_DIR
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - $TF_DIR/tfplan
  only:
    - main

# Stage 4: terraform apply (manual approval required)
terraform_apply:
  stage: apply
  script:
    - cd $TF_DIR
    - terraform apply -auto-approve tfplan
  dependencies:
    - terraform_plan
  when: manual
  only:
    - main
