variables:
  TF_DIR: "GitLab/devops_first"

stages:
  - init
  - plan
  - apply

init:
  stage: init
  image:
    name: hashicorp/terraform:1.6.6
    entrypoint: ["/bin/sh", "-c"]
  script:
    - cd $TF_DIR
    - terraform init

plan:
  stage: plan
  image: hashicorp/terraform:1.6.6
  script:
    - echo ">>> Current working directory:"
    - pwd
    - echo ">>> Listing repo root:"
    - ls -la
    - echo ">>> Listing GitLab/devops_first directory:"
    - ls -la GitLab/devops_first || echo "No such directory"
    - cd GitLab/devops_first
    - pwd
    - ls -la
    - terraform init
    - terraform plan -out=tfplan


apply:
  stage: apply
  image: hashicorp/terraform:1.6.6
  when: manual
  script:
    - cd $TF_DIR
    - terraform apply -auto-approve tfplan
