image:
  name: hashicorp/terraform:1.5.7
  entrypoint: [""]

before_script:
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - cd GitLab/devops_first   # 👈 go into the folder where your .tf files live
  - rm -rf .terraform
  - terraform init

stages:
  - validate
  - plan
  - apply
  - destroy

terraform_validate:
  stage: validate
  script:
    - cd GitLab/devops_first
    - terraform validate
  only:
    - main

terraform_plan:
  stage: plan
  script:
    - cd GitLab/devops_first
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - GitLab/devops_first/tfplan
  only:
    - main

terraform_apply:
  stage: apply
  script:
    - cd GitLab/devops_first
    - terraform apply -auto-approve tfplan
  dependencies:
    - terraform_plan
  when: manual
  only:
    - main

terraform_destroy:
  stage: destroy
  script:
    - cd GitLab/devops_first
    - terraform destroy -auto-approve
  when: manual
  only:
    - main
