variables:
  TF_DIR: "GitLab/devops_first"

stages:
  - init
  - validate
  - plan

init:
  image:
    name: hashicorp/terraform:1.6.6
    entrypoint: [""]
  stage: init
  script:
    - cd $TF_DIR
    - terraform init -backend=false

validate:
  image:
    name: hashicorp/terraform:1.6.6
    entrypoint: [""]
  stage: validate
  script:
    - cd $TF_DIR
    - terraform validate

plan:
  image:
    name: hashicorp/terraform:1.6.6
    entrypoint: [""]
  stage: plan
  script:
    - cd $TF_DIR
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - $TF_DIR/tfplan
