image: hashicorp/terraform:1.5.7

stages:
  - init
  - validate
  - plan
  - apply

# Stage 1: terraform init
terraform_init:
  stage: init
  script:
    - cd GitLab/devops_first
    - terraform init
  only:
    - main

# Stage 2: terraform validate
terraform_validate:
  stage: validate
  script:
    - cd GitLab/devops_first
    - terraform validate
  only:
    - main

# Stage 3: terraform plan
terraform_plan:
  stage: plan
  script:
    - cd GitLab/devops_first
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - GitLab/devops_first/tfplan
  only:
    - main

# Stage 4: terraform apply
terraform_apply:
  stage: apply
  script:
    - cd GitLab/devops_first
    - terraform apply -auto-approve tfplan
  dependencies:
    - terraform_plan
  only:
    - main
  when: manual
